CREATE TABLE Towns (
	Id INT IDENTITY PRIMARY KEY,
	Name VARCHAR(20) NOT NULL
)

CREATE TABLE Addresses (
	Id INT IDENTITY PRIMARY KEY,
	AddressText VARCHAR(200) NOT NULL,
	TownID INT FOREIGN KEY REFERENCES Towns(Id),
)

CREATE TABLE Departments (
	Id INT IDENTITY PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
)

CREATE TABLE Employees (
	Id INT IDENTITY PRIMARY KEY,
	FirstName VARCHAR(20) NOT NULL,
	MiddleName VARCHAR(20),
	LastName VARCHAR(20) NOT NULL,
	JobTitle VARCHAR(20),
	DepartmentId INT FOREIGN KEY REFERENCES Departments(Id),
	HireDate Date,
	Salary INT NOT NULL,
	AddressId INT FOREIGN KEY REFERENCES Addresses(Id)
)