CREATE TABLE Clients (
	ClientId INT IDENTITY NOT NULL PRIMARY KEY,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	Phone CHAR(12) NOT NULL CHECK(LEN(Phone) = 12),
)

CREATE TABLE Mechanics (
	MechanicId INT IDENTITY NOT NULL PRIMARY KEY,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	[Address] VARCHAR(255) NOT NULL,
)

CREATE TABLE Models (
	ModelId INT IDENTITY NOT NULL PRIMARY KEY,
	[Name] VARCHAR(50) UNIQUE,
)

CREATE TABLE Jobs (
	JobId INT IDENTITY NOT NULL PRIMARY KEY,
	ModelId INT NOT NULL FOREIGN KEY REFERENCES Models(ModelId),
	[Status] VARCHAR(11) NOT NULL DEFAULT 'Pending' CHECK ([Status] IN ('Pending', 'In Progress', 'Finished')) ,
	ClientId INT NOT NULL FOREIGN KEY REFERENCES Clients(ClientId),
	MechanicId INT FOREIGN KEY REFERENCES Mechanics(MechanicId),
	IssueDate DATE NOT NULL,
	FinishDate DATE,
)

CREATE TABLE Orders (
	OrderId INT IDENTITY NOT NULL PRIMARY KEY,
	JobId INT NOT NULL FOREIGN KEY REFERENCES Jobs(JobId),
	IssueDate DATE,
	Delivered BIT NOT NULL DEFAULT 0,
)

CREATE TABLE Vendors (
	VendorId INT IDENTITY NOT NULL PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL UNIQUE,
)

CREATE TABLE Parts (
	PartId INT IDENTITY NOT NULL PRIMARY KEY,
	SerialNumber VARCHAR(50) NOT NULL UNIQUE,
	[Description] VARCHAR(255),
	Price DECIMAL(18,2) NOT NULL CHECK(Price <= 9999.99 AND Price > 0),
	VendorId INT NOT NULL FOREIGN KEY REFERENCES Vendors(VendorId),
	StockQty INT NOT NULL DEFAULT 0 CHECK(StockQty >= 0),
)

CREATE TABLE OrderParts (
	OrderId INT NOT NULL FOREIGN KEY REFERENCES Orders(OrderId),
	PartId INT NOT NULL FOREIGN KEY REFERENCES Parts(PartId),
	Quantity INT NOT NULL DEFAULT 1 CHECK (Quantity > 0 ),
	CONSTRAINT PK_OrderParts PRIMARY KEY (OrderId, PartId),
)

CREATE TABLE PartsNeeded(
	JobId INT NOT NULL FOREIGN KEY REFERENCES Jobs(JobId),
	PartId INT NOT NULL FOREIGN KEY REFERENCES Parts(PartId),
	Quantity INT NOT NULL DEFAULT 1 CHECK (Quantity > 0),
	CONSTRAINT PK_PartsNeeded PRIMARY KEY (JobId, PartId),
)
