CREATE TABLE Passengers (
	Id INT IDENTITY NOT NULL PRIMARY KEY,
	FullName VARCHAR(100) NOT NULL UNIQUE,
	Email VARCHAR(50) NOT NULL UNIQUE
)

CREATE TABLE Pilots (
	Id INT IDENTITY NOT NULL PRIMARY KEY,
	FirstName VARCHAR(30) NOT NULL UNIQUE,
	LastName VARCHAR(30) NOT NULL UNIQUE,
	Age TINYINT NOT NULL CHECK (Age BETWEEN 21 AND 62),
	Rating FLOAT CHECK (Rating BETWEEN 0.0 AND 10.0)
)

CREATE TABLE AircraftTypes (
	Id INT IDENTITY NOT NULL PRIMARY KEY,
	TypeName VARCHAR(30) NOT NULL UNIQUE
)

CREATE TABLE Aircraft (
	Id INT IDENTITY NOT NULL PRIMARY KEY,
	Manufacturer VARCHAR(25) NOT NULL,
	Model VARCHAR(30) NOT NULL,
	[Year] INT NOT NULL,
	FlightHours INT,
	Condition CHAR(1) NOT NULL CHECK (LEN(Condition) = 1),
	TypeId INT NOT NULL FOREIGN KEY REFERENCES AircraftTypes(Id)
)

CREATE TABLE PilotsAircraft (
	AircraftId INT NOT NULL FOREIGN KEY REFERENCES Aircraft(Id),
	PilotId INT NOT NULL FOREIGN KEY REFERENCES Pilots(Id),
	CONSTRAINT PK_PilotsAircraft PRIMARY KEY(AircraftId, PilotId)
)

CREATE TABLE Airports (
	Id INT IDENTITY NOT NULL PRIMARY KEY,
	AirportName VARCHAR(70) NOT NULL UNIQUE,
	Country VARCHAR(100) NOT NULL UNIQUE
)

CREATE TABLE FlightDestinations (
	Id INT IDENTITY NOT NULL PRIMARY KEY,
	AirportId INT NOT NULL FOREIGN KEY REFERENCES Airports(Id),
	[Start] DATETIME NOT NULL,
	AircraftId INT NOT NULL FOREIGN KEY REFERENCES Aircraft(Id),
	PassengerId INT NOT NULL FOREIGN KEY REFERENCES Passengers(Id),
	TicketPrice DECIMAL (18, 2) NOT NULL DEFAULT 15
)